image: debian/oldstable
packages:
  - rsync
  - python3-pip
secrets:
  - 463872c8-309d-4d42-a3b7-e0588cb66204
  - a6db2c26-335f-4a97-bec4-445f09aeda3c
tasks:
  - install: |
      . ~/.codegouvfr-fetch-data-env
      cd codegouvfr-fetch-data
      rsync -e "ssh -o StrictHostKeyChecking=no" -av communs.numerique.gouv.fr:/home/build/websites/codegouvfr-data/ data/
      mkdir -p data/{libraries,organizations,repositories}/{csv,json}
      pip3 install -r requirements.txt
      python3 fetch.py
      python3 stats.py
  - upload: |
      cd codegouvfr-fetch-data
      rsync -e "ssh -o StrictHostKeyChecking=no" -av data/ communs.numerique.gouv.fr:/home/build/websites/codegouvfr-data/
triggers:
  - action: email
    condition: failure
    to: bastien.guerry@data.gouv.fr
